version: '3.7'
services:
  php-latest:
    image: "sheaxiang/docker:php-latest"
    ports:
      - "8000-8020:8000-8020"
    volumes:
      - ./src:/var/www/html
      - ./conf/php/latest/php.ini:/usr/local/etc/php/php.ini:rw
    restart: always
    links:
      - mysql-latest
  nginx-latest:
    image: "nginx"
    ports:
      - "80:80"
    privileged: true
    volumes:
      - ./src:/usr/share/nginx/html
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/log/:/var/log/nginx/:rw
    links:
      - php-latest
  mysql-latest:
    image: "sheaxiang/docker:mysql-latest"
    ports:
      - "3305:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql:rw
      - ./conf/mysql/mysql-latest:/etc/mysql/conf.d:rw
      - ./data/mysql/sock:/var/run/mysqld:rw # remove when windows.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here

  redis-latest:
    image: "sheaxiang/docker:redis-latest"
    ports:
      - "6378:6379"
    volumes:
      - ./data/redis/data:/var/lib/redis:rw
    sysctls:
        net.core.somaxconn: 65535
    restart: always
